# Generated by Django 3.1.5 on 2021-01-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_auto_20210130_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
