# Generated by Django 3.1.5 on 2021-04-29 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_voidnode_voidtree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voidnode',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.voidnode'),
        ),
    ]
