# Generated by Django 3.1.5 on 2021-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inVoid',
            field=models.BooleanField(default=False),
        ),
    ]
