# Generated by Django 3.1.5 on 2021-04-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_invoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voidAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
