# Generated by Django 3.1.5 on 2021-04-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_voidadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voidPoints',
            field=models.IntegerField(default=0),
        ),
    ]
